### ISSUE TITLE
Query with invalid types still return empty data

### ISSUE THREAD

**Issue by havran** [drupal-graphql/graphql-apq#3]
I have query which is not implemented on Drupal (new content type is not created) but this query still work - returns empty data. If i test same query in /graphql/explorer i get error:

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">LogicException</em>: Missing type ParagraphBoxHeader. in <em class="placeholder">Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase-&gt;getType()</em> (line <em class="placeholder">421</em> of <em class="placeholder">modules/contrib/graphql/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php</em>). <pre class="backtrace">Drupal\graphql\Plugin\GraphQL\Schemas\SchemaPluginBase-&gt;Drupal\graphql\Plugin\GraphQL\Schemas\{closure}(&#039;ParagraphBoxHeader&#039;) (Line: 319)
```

I use Angular app as frontend with modiffied Apollo client which first try GET query and then (if is not stored in apq_query_map) send query through POST. But this post still return some data:

```
{"data":[]}
```

I think this should return some error. Thanks.

**Comment by havran** [comment]
Problem is related with empty validatorRules:

https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php#L279

We need add validator rules for first query execution.

**Comment by havran** [comment]
PR https://github.com/lucasconstantino/drupal-graphql-apq/pull/4

**Comment by sebas5384** [comment]
moved to PR #9
