### ISSUE TITLE
Persisted Queries are getting cached in Drupal

### ISSUE THREAD

**Issue by anuragshah17** [drupal-graphql/graphql-apq#5]
We are using this module, getting this issue . 

Sending new hash with query , registers hash and responds with Data. 
When trying to send query with only hash(already registered) and variable , getting response PersistedQueryNotFound. After clearing cache getting response as expected. 

Same issue was resolved in Graphql module :- 
https://github.com/drupal-graphql/graphql/pull/483
 
Can we also implement similar approach?

**Comment by lucasconstantino** [comment]
I'm not really working with Drupal nowadays, so I would really appreciate a pull-request on that.

Also, I personally know @sebas5384, he did the reviews on the mentioned task, perhaps he can help with something here, though I can't confirm his availability.

**Comment by anuragshah17** [comment]
Closing this issue , there is already a PR for this and it works fine. 

https://github.com/lucasconstantino/drupal-graphql-apq/pull/1/
